### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by mesut** [HasanBulbul/SpringMvcHibernate#1]
1-domain objects must override hash and equals methods.

2-import java package then use class of the imported package.Employees  implements  java.io.Serializable remove package name.

3-don’t print stack trace of exception.use a logger tech like slf4j for logging exception

4-No need code and page comment.Please remove them

5-you should read values from properties file in hibernate.cfg file

**Comment by hsnblbl** [comment]
Thanks for the feedback
